// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_expert = "CgkIvZqi8NgeEAIQCQ"; // <GPGSID>
        public const string achievement_unlimited_power = "CgkIvZqi8NgeEAIQDw"; // <GPGSID>
        public const string achievement_pro = "CgkIvZqi8NgeEAIQCA"; // <GPGSID>
        public const string achievement_car_connoisseur = "CgkIvZqi8NgeEAIQDA"; // <GPGSID>
        public const string achievement_rookie = "CgkIvZqi8NgeEAIQBw"; // <GPGSID>
        public const string achievement_escape_artist = "CgkIvZqi8NgeEAIQBg"; // <GPGSID>
        public const string achievement_monstrous_acquisition = "CgkIvZqi8NgeEAIQDQ"; // <GPGSID>
        public const string leaderboard_two_ways_mode = "CgkIvZqi8NgeEAIQAw"; // <GPGSID>
        public const string leaderboard_chaos_mode = "CgkIvZqi8NgeEAIQBQ"; // <GPGSID>
        public const string achievement_master = "CgkIvZqi8NgeEAIQCg"; // <GPGSID>
        public const string leaderboard_normal_mode = "CgkIvZqi8NgeEAIQAg"; // <GPGSID>
        public const string achievement_master_of_the_multiplier = "CgkIvZqi8NgeEAIQDg"; // <GPGSID>
        public const string leaderboard_time_mode = "CgkIvZqi8NgeEAIQBA"; // <GPGSID>
        public const string achievement_first_ride = "CgkIvZqi8NgeEAIQCw"; // <GPGSID>

}

